### ISSUE TITLE
作者你好，当我运行代码时，尝试将 data = normalize(data)          negative_data = normalize(negative_data) 这两行代码注释掉，发现并不能降低后门ASR，请问这两行代码有什么特殊的目的吗

### ISSUE THREAD

**Issue by XXiaoY** [Zhihao151/MCL#1]
作者你好，当我运行代码时，尝试将 data = normalize(data) negative_data = normalize(negative_data) 这两行代码注释掉，发现并不能降低后门ASR，请问这两行代码有什么特殊的目的吗 #1

**Comment by yzh1033726970** [comment]
感谢你对我们工作的关注。normalize是训练模型时对数据做得一种预处理工作，在训练和推理阶段需要保持一致，一般会放在加载数据集的transform里。但在我们的代码中，我们并没有放在transform里，是单独处理的，因此需要存在这两行代码，用于保证训练和推理阶段对数据预处理操作的一致性。
再次感谢您的关注，如果我们的工作对您有所启发，欢迎引用我们的文章。
